### ISSUE TITLE
22/08/24 Cokesh's To Do

### ISSUE THREAD

**Issue by cokesh** [DalmoTeam/GOLFLEARN#3]
08/24
- [x] ToDo 작성하기
- [x] 아침일찍 와서 공부하기
- [x] JPA쭉 훑기 - 책없어서 유투브로
- [x] 플젝 - DTO
- [x] microservice 배경

> Discipline + Focus + Action = Success

**Comment by cokesh** [comment]
good cokesh

**Comment by myCYWORLD** [comment]
ohhhhhhhh....goo,,,d
