### ISSUE TITLE
22/09/01~02 Cokesh's To-Do

### ISSUE THREAD

**Issue by cokesh** [DalmoTeam/GOLFLEARN#50]
- [ ] noticeBoardCommentRepository
- [ ] noticeBoardLikeRepository  
- [ ] api 알아보기 (챗봇api)
- [ ] 아싸 잘 이겨내기 🍚은🍙으로 🗣은⌨️로 ⍥

**Comment by 1futuro** [comment]
아싸 잘 이겨냄?

**Comment by cokesh** [comment]
전혀 못이겨냄
